# Generated by Django 3.2.5 on 2022-02-23 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('disease_name', models.CharField(max_length=200)),
                ('disease_caption', models.TextField(blank=True)),
                ('disease_description', models.TextField(blank=True)),
                ('disease_symptoms', models.TextField(blank=True)),
                ('disease_precautions', models.TextField(blank=True)),
                ('disease_medication', models.TextField(blank=True)),
                ('disease_image', models.ImageField(blank=True, help_text='crop image as square before upload to get uniform size in the page', null=True, upload_to='')),
                ('add_disease_to_home', models.BooleanField(blank=True, default=False, help_text='Yes will enable to display it on home page', null=True)),
            ],
        ),
    ]
