# Generated by Django 3.2.5 on 2022-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0002_helpline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpline',
            name='country',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='helpline',
            name='helpline_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='helpline',
            name='organization',
            field=models.CharField(max_length=500),
        ),
    ]
