# Generated by Django 3.2.5 on 2022-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0003_auto_20220228_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=200)),
                ('reviewer_email', models.EmailField(blank=True, max_length=200)),
                ('reviewer_message', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('tool_accuracy', models.CharField(max_length=200)),
                ('tool_technology', models.CharField(max_length=200)),
                ('tool_detail', models.TextField(max_length=4000)),
                ('tool_link', models.CharField(max_length=200)),
            ],
        ),
    ]
