# Generated by Django 3.2.5 on 2022-03-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0004_contactmessage_diagnosistool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=300)),
                ('diet_category', models.CharField(max_length=100)),
                ('veg_food', models.BooleanField(blank=True, default=True, null=True)),
                ('Calories', models.CharField(max_length=100)),
                ('Fats', models.CharField(max_length=100)),
                ('Proteins', models.CharField(max_length=100)),
                ('Iron', models.CharField(max_length=100)),
                ('Calcium', models.CharField(max_length=100)),
                ('Sodium', models.CharField(max_length=100)),
                ('Potassium', models.CharField(max_length=100)),
                ('Carb', models.CharField(max_length=100)),
                ('Fibres', models.CharField(max_length=100)),
                ('Sugars', models.CharField(max_length=100)),
            ],
        ),
    ]
