# Generated by Django 3.2.5 on 2022-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0005_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='diabetic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
