# Generated by Django 3.2.5 on 2022-05-18 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0006_food_diabetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_user', models.CharField(blank=True, max_length=300)),
                ('rating_tool', models.CharField(blank=True, max_length=300)),
                ('rating_parameter', models.CharField(blank=True, max_length=100)),
                ('rating_message', models.TextField(blank=True)),
                ('rating_time', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
