# Generated by Django 3.2.5 on 2022-05-20 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0007_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainTumorDiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300)),
                ('Mean', models.CharField(blank=True, max_length=300)),
                ('Variance', models.CharField(blank=True, max_length=300)),
                ('StandardDeviation', models.CharField(blank=True, max_length=300)),
                ('Entropy', models.CharField(blank=True, max_length=300)),
                ('Skewness', models.CharField(blank=True, max_length=300)),
                ('Kurtosis', models.CharField(blank=True, max_length=300)),
                ('Contrast', models.CharField(blank=True, max_length=300)),
                ('Energy', models.CharField(blank=True, max_length=300)),
                ('ASM', models.CharField(blank=True, max_length=300)),
                ('Homogeneity', models.CharField(blank=True, max_length=300)),
                ('Dissimilarity', models.CharField(blank=True, max_length=300)),
                ('Correlation', models.CharField(blank=True, max_length=300)),
                ('Coarseness', models.CharField(blank=True, max_length=300)),
                ('PSNR', models.CharField(blank=True, max_length=300)),
                ('SSIM', models.CharField(blank=True, max_length=300)),
                ('MSE', models.CharField(blank=True, max_length=300)),
                ('DC', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(blank=True, max_length=300)),
                ('risk_score', models.CharField(blank=True, max_length=300)),
                ('Diagnosis_Date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesDiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300)),
                ('Pregnancies', models.CharField(blank=True, max_length=300)),
                ('Glucose', models.CharField(blank=True, max_length=300)),
                ('BloodPressure', models.CharField(blank=True, max_length=300)),
                ('SkinThickness', models.CharField(blank=True, max_length=300)),
                ('Insulin', models.CharField(blank=True, max_length=300)),
                ('BMI', models.CharField(blank=True, max_length=300)),
                ('DiabetesPedigreeFunction', models.CharField(blank=True, max_length=300)),
                ('Age', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(blank=True, max_length=300)),
                ('risk_score', models.CharField(blank=True, max_length=300)),
                ('Diagnosis_Date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HeartDiseaseDiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300)),
                ('age', models.CharField(blank=True, max_length=300)),
                ('sex', models.CharField(blank=True, max_length=300)),
                ('cp', models.CharField(blank=True, max_length=300)),
                ('trestbps', models.CharField(blank=True, max_length=300)),
                ('col', models.CharField(blank=True, max_length=300)),
                ('fbs', models.CharField(blank=True, max_length=300)),
                ('restecg', models.CharField(blank=True, max_length=300)),
                ('exang', models.CharField(blank=True, max_length=300)),
                ('thalach', models.CharField(blank=True, max_length=300)),
                ('slope', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(blank=True, max_length=300)),
                ('risk_score', models.CharField(blank=True, max_length=300)),
                ('Diagnosis_Date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LiverDiseaseDiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300)),
                ('Age', models.CharField(blank=True, max_length=300)),
                ('Gender', models.CharField(blank=True, max_length=300)),
                ('Total_Bilirubin', models.CharField(blank=True, max_length=300)),
                ('Direct_Bilirubin', models.CharField(blank=True, max_length=300)),
                ('Alkaline_Phosphotase', models.CharField(blank=True, max_length=300)),
                ('Alamine_Aminotransferase', models.CharField(blank=True, max_length=300)),
                ('Aspartate_Aminotransferase', models.CharField(blank=True, max_length=300)),
                ('Total_Protiens', models.CharField(blank=True, max_length=300)),
                ('Albumin', models.CharField(blank=True, max_length=300)),
                ('Albumin_and_Globulin_Ratio', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(blank=True, max_length=300)),
                ('risk_score', models.CharField(blank=True, max_length=300)),
                ('Diagnosis_Date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
