# Generated by Django 3.2.5 on 2022-05-22 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0009_auto_20220520_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_on', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('problem', models.CharField(max_length=200)),
                ('problem_description', models.TextField(blank=True)),
                ('problem_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
