# Generated by Django 3.2.5 on 2022-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0010_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_username', models.CharField(max_length=1000)),
                ('expert_designation', models.CharField(max_length=2000)),
                ('expert_specialization', models.CharField(max_length=4000)),
                ('expert_address', models.CharField(max_length=4000)),
                ('expert_contact', models.CharField(max_length=1000)),
                ('expert_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
