# Generated by Django 3.2.5 on 2022-05-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0011_healthcareexpert'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareexpert',
            name='expert_email',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='healthcareexpert',
            name='expert_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
