# Generated by Django 3.2.5 on 2022-05-23 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0012_auto_20220522_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('preferred_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('booked_by', models.CharField(max_length=1000)),
                ('user_email', models.CharField(max_length=1000)),
                ('expert_username', models.CharField(max_length=1000)),
                ('expert_email', models.CharField(max_length=1000)),
                ('problem', models.TextField()),
                ('accepted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
