# Generated by Django 3.2.5 on 2022-05-26 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0013_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('age', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('diabetic', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
