# Generated by Django 3.2.5 on 2022-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0014_medicalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='posted_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
