# Generated by Django 3.2.5 on 2022-05-26 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0015_alter_disease_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='posted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
